# Generated by Django 3.1.6 on 2021-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='interest',
            field=models.ManyToManyField(through='Landing.UsersInterest', to='Landing.Interest'),
        ),
    ]
