# Generated by Django 3.1.6 on 2021-02-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210213_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='photo',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
    ]
